# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

  # The part that publishes the compiled mod
  publish:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: read gradle.properties
        uses: madhead/read-java-properties@latest
        id: gradle
        with:
          file: gradle.properties
          all: true
        env:
          JAVA_HOME: /usr/local/openjdk-17
      - name: publish mod
        uses: Kir-Antipov/mc-publish@v2.1
        with:

          name: ${{ steps.gradle.outputs.release_fancyname }}
          version: ${{ steps.gradle.outputs.mod_version }}
          version-type: release

          game-versions: |
            ${{ steps.gradle.outputs.minecraft_version }}
          java: |
            17
            18
          dependencies: |
            fabric-api

          changelog-file: CHANGELOG.md

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.TOKEN_GITHUB }}
